wx_icon_dict = {0:"https://www.bmkg.go.id/asset/img/weather_icon/ID/cerah-am.png",
                1:"https://www.bmkg.go.id/asset/img/weather_icon/ID/cerah%20berawan-am.png",
                2:"https://www.bmkg.go.id/asset/img/weather_icon/ID/cerah%20berawan-am.png",
                3:"https://www.bmkg.go.id/asset/img/weather_icon/ID/berawan-am.png",
                4:"https://www.bmkg.go.id/asset/img/weather_icon/ID/berawan tebal-am.png",
                10:"https://www.bmkg.go.id/asset/img/weather_icon/ID/asap-am.png",
                45:"https://www.bmkg.go.id/asset/img/weather_icon/ID/kabut-am.png",
                60:"https://www.bmkg.go.id/asset/img/weather_icon/ID/hujan%20ringan-am.png",
                61:"https://www.bmkg.go.id/asset/img/weather_icon/ID/hujan%20sedang-am.png",
                63:"https://www.bmkg.go.id/asset/img/weather_icon/ID/hujan%20lebat-am.png",
                95:"https://www.bmkg.go.id/asset/img/weather_icon/ID/hujan%20petir-am.png",
                97:"https://www.bmkg.go.id/asset/img/weather_icon/ID/hujan%20petir-am.png"}
wx_caption_dict = {0:"Cerah",
                1:"Cerah Berawan",
                2:"Cerah Berawan",
                3:"Berawan",
                4:"Berawan Tebal",
                10:"Asap",
                45:"Kabut",
                60:"Hujan Ringan",
                61:"Hujan Sedang",
                63:"Hujan Lebat",
                95:"Hujan Petir",
                97:"Hujan Petir"}
wind_caption_dict = {"N":"Utara",
                     "NE":"Timur Laut",
                     "E":"Timur",
                     "SE":"Tenggara",
                     "S":"Selatan",
                     "SW":"Barat Daya",
                     "W":"Barat",
                     "NW":"Barat Laut"}